- src: galaxyproject.galaxy
  version: 0.10.21
- src: galaxyproject.nginx
  version: 0.7.1
- src: galaxyproject.postgresql
  version: 1.1.2
- src: galaxyproject.postgresql_objects
  version: 1.2.0
- src: galaxyproject.miniconda
  version: 0.3.1
- src: galaxyproject.slurm
  version: 1.0.4
- src: https://github.com/ARTbio/ansible-galaxy-tools.git
  name: install.galaxy-tools
