- src: galaxyproject.galaxy
  version: 0.12.0     # meilleure compatibilité Gravity et handlers
- src: galaxyproject.nginx
  version: 0.8.0
- src: galaxyproject.postgresql
  version: 1.3.0
- src: galaxyproject.postgresql_objects
  version: 1.3.1
- src: galaxyproject.miniconda
  version: 0.4.0
- src: galaxyproject.slurm
  version: 1.1.0
- src: https://github.com/ARTbio/ansible-galaxy-tools.git
  name: install.galaxy-tools
