- src: galaxyproject.galaxy
  version: 0.12.0     # meilleure compatibilité Gravity et handlers
- src: galaxyproject.nginx
  version: 1.0.0
- src: galaxyproject.postgresql
  version: 1.1.8
- src: galaxyproject.postgresql_objects
  version: 1.2.1
- src: galaxyproject.miniconda
  version: 0.3.4
- src: galaxyproject.slurm
  version: 1.0.5
- src: https://github.com/ARTbio/ansible-galaxy-tools.git
  name: install.galaxy-tools
