tools:
- name: fetch_fasta_from_ncbi
  owner: artbio
  tool_panel_section_label: 'ARTbio tools'
  tool_panel_section_id: artbio_tools
  tool_shed_url: https://toolshed.g2.bx.psu.edu

- name: sr_bowtie
  owner: artbio
  tool_panel_section_label: 'ARTbio tools'
  tool_panel_section_id: artbio_tools
  tool_shed_url: https://toolshed.g2.bx.psu.edu

- name: data_manager_fetch_genome_dbkeys_all_fasta
  owner: devteam
  tool_shed_url: https://toolshed.g2.bx.psu.edu

- name: bowtie_index_builder_data_manager
  owner: artbio
  tool_shed_url: https://toolshed.g2.bx.psu.edu

- name: samtools_view
  tool_panel_section_label: 'SAMTOOLS'
  tool_panel_section_id: samtools
  tool_shed_url: https://toolshed.g2.bx.psu.edu
