tools:
- name: fastqc
  owner: devteam
  tool_panel_section_id: quality_control
  tool_panel_section_label: Quality Control
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: multiqc
  owner: iuc
  tool_panel_section_id: quality_control
  tool_panel_section_label: Quality Control
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: fastp
  owner: iuc
  tool_panel_section_id: quality_control
  tool_panel_section_label: Quality Control
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: cutadapt
  owner: lparsons
  tool_panel_section_id: trimming
  tool_panel_section_label: Trimming
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: bowtie2
  owner: devteam
  tool_panel_section_id: mapping
  tool_panel_section_label: Mapping
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: hisat2
  owner: iuc
  tool_panel_section_id: mapping
  tool_panel_section_label: Mapping
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_view
  owner: iuc
  tool_panel_section_id: sam_bam
  tool_panel_section_label: SAM/BAM
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_flagstat
  owner: devteam
  tool_panel_section_id: sam_bam
  tool_panel_section_label: SAM/BAM
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: picard
  owner: devteam
  tool_panel_section_id: sam_bam
  tool_panel_section_label: SAM/BAM
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: featurecounts
  owner: iuc
  tool_panel_section_id: rna_seq
  tool_panel_section_label: RNA-Seq
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: deseq2
  owner: iuc
  tool_panel_section_id: rna_seq
  tool_panel_section_label: RNA-Seq
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: ncbi_blast_plus
  owner: devteam
  tool_panel_section_id: homology
  tool_panel_section_label: Homology
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: bedtools
  owner: iuc
  tool_panel_section_id: bed_tools
  tool_panel_section_label: BED Tools
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: seqtk
  owner: iuc
  tool_panel_section_id: fasta_fastq
  tool_panel_section_label: FASTA/FASTQ
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: text_processing
  owner: bgruening
  tool_panel_section_id: text_manipulation
  tool_panel_section_label: Text Manipulation
  tool_shed_url: toolshed.g2.bx.psu.edu
