#!/usr/bin/env python3
"""
galaxy_tools_export.py
======================
Generate both tool_list.yml (Ephemeris) and job_tool_routing.yml
from a single GET /api/tools?in_panel=true call.

Usage:
    python3 galaxy_tools_export.py <galaxy_url> [options]

Options:
    --dest <name>      Default Slurm destination (default: cluster_1)
    --tool-list <path> Output path for tool_list.yml (default: tool_list.yml)
    --routing <path>   Output path for job_tool_routing.yml (default: job_tool_routing.yml)
    --no-revisions     Omit changeset_revision from tool_list (install latest)

Examples:
    python3 galaxy_tools_export.py https://usegalaxy.sorbonne-universite.fr
    python3 galaxy_tools_export.py https://usegalaxy.sorbonne-universite.fr --dest cluster_8
"""

import json
import sys
import urllib.request
from collections import OrderedDict
from pathlib import Path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def fetch_panel(galaxy_url: str) -> list:
    url = galaxy_url.rstrip("/") + "/api/tools?in_panel=true"
    print(f"[fetch] {url}", file=sys.stderr)
    with urllib.request.urlopen(url, timeout=30) as resp:
        return json.load(resp)


def short_id(full_id: str) -> str:
    """toolshed.../tool_id/version → tool_id   |   builtin → builtin"""
    parts = full_id.split("/")
    return parts[-2] if len(parts) >= 2 else full_id


SKIP_PREFIXES = ("CONVERTER_", "__")

def is_user_tool(full_id: str) -> bool:
    return not any(full_id.startswith(p) for p in SKIP_PREFIXES)


# ---------------------------------------------------------------------------
# Parse
# ---------------------------------------------------------------------------

def parse_panel(panel: list):
    """
    Returns:
        toolshed_tools : OrderedDict  repo_key → {name, owner, tool_shed,
                                                   revisions: set, section_id}
        routing_tools  : list of {short_id, repo_name, section_name}
    """
    toolshed_tools = OrderedDict()   # keyed by (name, owner, tool_shed)
    routing_tools  = []
    seen_sids      = set()

    for section in panel:
        if not isinstance(section, dict):
            continue
        section_name = section.get("name", "")
        section_id   = section.get("id", "")

        for elem in section.get("elems", []):
            if not isinstance(elem, dict):
                continue
            if elem.get("model_class") != "Tool":
                continue

            full = elem.get("id", "")
            if not is_user_tool(full):
                continue

            sid = short_id(full)
            tsr = elem.get("tool_shed_repository")

            # ── tool_list entry (toolshed tools only, deduplicated by repo) ──
            if tsr:
                key = (tsr["name"], tsr["owner"], tsr["tool_shed"])
                if key not in toolshed_tools:
                    toolshed_tools[key] = {
                        "name":       tsr["name"],
                        "owner":      tsr["owner"],
                        "tool_shed":  tsr["tool_shed"],
                        "revisions":  set(),
                        "section_id": section_id,
                    }
                rev = tsr.get("changeset_revision")
                if rev:
                    toolshed_tools[key]["revisions"].add(rev)

            # ── routing entry (all user tools, deduplicated by short_id) ────
            if sid not in seen_sids:
                seen_sids.add(sid)
                routing_tools.append({
                    "short_id":    sid,
                    "repo_name":   tsr["name"] if tsr else "",
                    "section":     section_name,
                })

    return list(toolshed_tools.values()), routing_tools


# ---------------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------------

def render_tool_list(repos: list, include_revisions: bool) -> str:
    lines = [
        "# Tool list generated by galaxy_tools_export.py",
        "# Install with: shed-tools install -g <url> -a <key> -t tool_list.yml",
        "tools:",
    ]
    current_section = None
    for r in repos:
        if r["section_id"] != current_section:
            current_section = r["section_id"]
            lines.append(f"")
            lines.append(f"  # panel section: {current_section}")
        lines.append(f"  - name: {r['name']}")
        lines.append(f"    owner: {r['owner']}")
        lines.append(f"    tool_panel_section_id: {r['section_id']}")
        lines.append(f"    tool_shed: {r['tool_shed']}")
        if include_revisions and r["revisions"]:
            lines.append(f"    revisions:")
            for rev in sorted(r["revisions"]):
                lines.append(f"      - {rev}")
    return "\n".join(lines)


def render_routing(tools: list, default_dest: str) -> str:
    lines = [
        "# job_tool_routing generated by galaxy_tools_export.py",
        "# Review and adjust destinations before committing.",
        "job_tool_routing:",
    ]
    current_section = None
    for t in tools:
        if t["section"] != current_section:
            current_section = t["section"]
            lines.append(f"")
            lines.append(f"  # --- {current_section} ---")
        comment = f"  # repo: {t['repo_name']}" if t["repo_name"] else ""
        lines.append(f'  - id: "{t["short_id"]}"')
        lines.append(f'    destination: "{default_dest}"{comment}')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args(argv):
    args = {
        "galaxy_url":       None,
        "dest":             "cluster_1",
        "tool_list_path":   "tool_list.yml",
        "routing_path":     "job_tool_routing.yml",
        "no_revisions":     False,
    }
    i = 1
    while i < len(argv):
        a = argv[i]
        if a == "--dest":            args["dest"] = argv[i+1]; i += 2
        elif a == "--tool-list":     args["tool_list_path"] = argv[i+1]; i += 2
        elif a == "--routing":       args["routing_path"] = argv[i+1]; i += 2
        elif a == "--no-revisions":  args["no_revisions"] = True; i += 1
        elif not a.startswith("--"): args["galaxy_url"] = a; i += 1
        else:                        i += 1
    return args


def main():
    args = parse_args(sys.argv)
    if not args["galaxy_url"]:
        print(__doc__)
        sys.exit(1)

    panel = fetch_panel(args["galaxy_url"])
    repos, routing = parse_panel(panel)

    print(f"[parse] {len(repos)} unique repos  |  {len(routing)} unique tool IDs",
          file=sys.stderr)

    tool_list_text = render_tool_list(repos, not args["no_revisions"])
    routing_text   = render_routing(routing, args["dest"])

    Path(args["tool_list_path"]).write_text(tool_list_text)
    Path(args["routing_path"]).write_text(routing_text)

    print(f"[write] {args['tool_list_path']}", file=sys.stderr)
    print(f"[write] {args['routing_path']}", file=sys.stderr)


if __name__ == "__main__":
    main()
