name: Build galaxyXpand docker image
on:
  push:
    branches-ignore:
      - master
      - readthedocs
  
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - uses: docker/setup-buildx-action@v2.4.1
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          docker build . # will run buildx